version: '3'

services:
  powerhour:
    image: powerhour:latest
    container_name: powerhour
    build:
      context: .
      dockerfile: Dockerfile
    env_file: powerhour.env
    command: /bin/bash run_module.sh
    volumes:
      - ./video_downloads:/usr/src/app/powerhour/generation/video_downloads

  webserver:
    image: powerhour:latest
    container_name: powerhour_webserver
    build:
      context: .
      dockerfile: Dockerfile
    env_file: powerhour.env
    ports:
      - "80:8000"
